### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by eoussama** [ScavengeSurvive/button#5]
I don't know if I'm doing anything wrong but the package simply refuses to work in any environment (testing or inclusion), whenever I try to run tests it seems that a few includes are missing, other than this, when I try installing the package into another package I get all sorts of missing includes errors (YSI, crashdetect, ... etc).

![image](https://user-images.githubusercontent.com/22644543/188517322-3c6147c2-5fbe-4006-ba8c-89a9325619ad.png)

**Comment by Southclaws** [comment]
I'm not sure what's up with this, did YSI change its directory structure?

**Comment by eoussama** [comment]
From what I understand, `pawn.json` is missing the version tag so it automatically installs `pawn-lang/YSI-Includes@5.x` where the folder structure changed immensely.

**Comment by Southclaws** [comment]
Yeah this is correct
